### ISSUE TITLE
Build failure when packaged with BlueSocket

### ISSUE THREAD

**Issue by robreuss** [Bouke/NetService#44]
I've run into a strange problem where if NetService and BlueSocket are both included as dependencies the build process hangs on the following line and brings down the whole OS:

`'Cdns_sd' avahi-compat-libdns_sd.pc: warning: prohibited flag(s): -D_REENTRANT`

If I modify the package to build with either of the two dependencies on their own, it builds just fine for each.  It only crashes when building with both dependencies.

I've created a simple project to demonstrate the failur.  You can comment/uncomment the individual dependencies to build with each dependency solo, and combine them to get the crash:

https://github.com/robreuss/CopyPackage.git

I'm running this on a Raspberry Pi 3b, Ubuntu 20.04.3, and Swift 5.5.  

It builds just fine when running in a VM using VMWare under macOS ARM.

This problem is a major blocker for me so any help would be most appreciated!  Thanks Bouke.

**Comment by Bouke** [comment]
I suppose this is caused by a compiler bug, I've come across various bugs in the RPi ARM Swift compiler. Often those were already fixed in the swift-arm repository and an update got me unblocked. I'm no compiler expert and haven't run into this particular issue myself.

I've used BlueSocket in the past but have switched to SwiftNIO instead. While I got that working eventually I found the migration frustrating as the API was only lightly documented, the Swift compiler errors confusing and async being a pain overall. But now that async is available I can only imagine things having improved since. Update: looking at the documentation I have no idea where to get started, it's only API docs. (Not saying you should ditch BlueSocket, just offering my 2 cents).

I've updated Swift to 5.5-01-debian-buster and I can compile your example just fine. It does hang for a few seconds on the line you mentioned, but does continue following that:
<details>
swift build
Fetching https://github.com/Kitura/BlueSocket.git
Fetching https://github.com/Bouke/NetService.git from cache
Fetched https://github.com/Kitura/BlueSocket.git (1.80s)
Fetched https://github.com/Bouke/NetService.git (1.81s)
Computing version for https://github.com/Bouke/NetService.git
Computed https://github.com/Bouke/NetService.git at 0.8.1 (0.67s)
Computing version for https://github.com/Kitura/BlueSocket.git
Computed https://github.com/Kitura/BlueSocket.git at 1.0.200 (0.54s)
Creating working copy for https://github.com/Bouke/NetService.git
Working copy of https://github.com/Bouke/NetService.git resolved at 0.8.1
Creating working copy for https://github.com/Kitura/BlueSocket.git
Working copy of https://github.com/Kitura/BlueSocket.git resolved at 1.0.200
'Socket' /home/pi/CopyPackage/.build/checkouts/BlueSocket: warning: Invalid Exclude '/home/pi/CopyPackage/.build/checkouts/BlueSocket/Sources/Socket/BlueSocket.xcworkspace': File not found.
'Socket' /home/pi/CopyPackage/.build/checkouts/BlueSocket: warning: Invalid Exclude '/home/pi/CopyPackage/.build/checkouts/BlueSocket/Sources/Socket/Sources/Info.plist': File not found.
'Socket' /home/pi/CopyPackage/.build/checkouts/BlueSocket: warning: Invalid Exclude '/home/pi/CopyPackage/.build/checkouts/BlueSocket/Sources/Socket/BlueSocket.xcodeproj': File not found.
'Socket' /home/pi/CopyPackage/.build/checkouts/BlueSocket: warning: Invalid Exclude '/home/pi/CopyPackage/.build/checkouts/BlueSocket/Sources/Socket/README.md': File not found.
'Socket' /home/pi/CopyPackage/.build/checkouts/BlueSocket: warning: Invalid Exclude '/home/pi/CopyPackage/.build/checkouts/BlueSocket/Sources/Socket/Sources/Socket.h': File not found.
'Cdns_sd' avahi-compat-libdns_sd.pc: warning: prohibited flag(s): -D_REENTRANT
/home/pi/CopyPackage/.build/checkouts/NetService/Sources/NetService/NetServiceDelegate.swift:4:37: warning: using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead
public protocol NetServiceDelegate: class {
                                    ^~~~~
                                    AnyObject
/home/pi/CopyPackage/.build/checkouts/NetService/Sources/NetService/NetServiceDelegate.swift:4:37: warning: using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead
public protocol NetServiceDelegate: class {
                                    ^~~~~
                                    AnyObject
/home/pi/CopyPackage/.build/checkouts/NetService/Sources/NetService/NetServiceBrowserDelegate.swift:4:44: warning: using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead
public protocol NetServiceBrowserDelegate: class {
                                           ^~~~~
                                           AnyObject
/home/pi/CopyPackage/.build/checkouts/NetService/Sources/NetService/NetServiceBrowserDelegate.swift:4:44: warning: using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead
public protocol NetServiceBrowserDelegate: class {
                                           ^~~~~
                                           AnyObject
[20/20] Build complete!
</details>

**Comment by robreuss** [comment]
Debian may be a workaround for me.  ElementalController (the framework at issue) is intended to be for public use, and I wouldn't want to have it be constrained to a specific distro on RPi, but there really hasn't been much interest in the framework anyway, so that might be a good compromise.  This issue is blocking from moving forward with work on a robot, and I just want to get past it and move forward with higher level functionality.

Can you confirm that the workaround is that I need to install Debian as the OS on the RPi, and then install Swift as described on the top of this page: [https://swift-arm.com/installSwift/](url)?

Thanks so much.

**Comment by robreuss** [comment]
Also, when you refer to Debian, are you effectively meaning the current version of Raspberry Pi OS?

**Comment by robreuss** [comment]
I went ahead and installed bullseye, and lo and behold it compiled!  Thanks so much.  I've put untold hours into trying to solve the problem, and as I recall I even tried using Raspberian in the past, but alas.  You made my day.

**Comment by robreuss** [comment]
Unfortunately, and this quite strange, after successfully compiling CopyPackage subsequent compilations fail, hanging the same way as described above.  This is quite mystifying to me.  I've re-cloned the package, and that does not solve the problem.  Would you mind seeing if you get the same behavior on your system?  Given that re-cloning does not solve the issue, since that would entirely reset the CopyPackage installation including any cached packages (akin to removing .build), I wonder if there is some type of state managed by git or swift outside the context of the installed package?  I'm not aware of anything like that.  

I'm not sure if this is a clue or not but I initially installed the 32-bit version of Raspberry Pi OS (Debian Bullseye) and was successfully compiling my ElementalController package but getting what appeared to be fatal NIO-related errors.  Oddly, I do not see the same successful compilation after I installed the 64-bit, in the hope that it would resolve the NIO-related errors.

I really appreciate any assistance you can offer!

**Comment by robreuss** [comment]
Unfortunately I've run into a problem.  I think CopyPackage compiled correctly for me on the first run, after a clean install of Debian Bullseye, but subsequent compiles with both packages still result in the crash described above.

What's interesting in a work-around I've figured out for the compile failure with both dependencies enabled in `Package.swift`.  If you comment out one dependency it successfully builds of course.  Then if you uncomment the second package, without cleaning the project, it will successfully compile with both.  My guess is that the first build put's a successfully compiled version of the dependency built on it's own into the cache, so when the project is built with both dependencies one of the two are pre-compiled.

While this is a good enough work-around for me to move forward with my personal project (which is great), it is obviously unacceptable in terms of the usefulness of my framework for public use in this OS/hardware context.  

Do you have thoughts on an approach to Package.swift that might have the same effect?  For example, is there a switch for `swift build` that might cause the SPM to resolve or build the dependencies in a way that compile a dependency on it's own?

Any help would be greatly appreciated!

**Comment by robreuss** [comment]
Okay, I believe I've found exactly the fix that I was hoping for above, a command line argument to `build` and `run` that handles dependencies in a different way:

`swift build -c release`

and

`swift run -c release`

They successfully compile my projects, including when the project has been cleaned.  They produce the following warning during compilation:

`Incremental compilation has been disabled: it is not compatible with whole module optimization`

Do you have thoughts on the meaning of that warning?  I have the general sense that it means some of the incremental optimizations for the edit, compile, debug cycle are disabled in favor of producing an optimized executable.

**Comment by Bouke** [comment]
Incremental compilation is very useful when developing; it allows for speedier compilations and shortens the change-build-validate cycle. For deployments it isn't useful as you'd want the release build anyway. Why WMO is failing the build is a question best asked experts themselves, for example on the [Swift forums](https://forums.swift.org/c/development/compiler/9).

Regarding 32-bit (from your earlier comment, now edited), I especially wanted to use 64-bit as that seems to require the least changes to get Swift working (32-bit is a bit of a lemon).

<details>

```
$ cat /etc/*release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ uname -a
Linux pi.local 5.10.11-v8+ #1399 SMP PREEMPT Thu Jan 28 12:14:03 GMT 2021 aarch64 GNU/Linux
```
</details>

**Comment by robreuss** [comment]
Thanks a lot.  I will post to the Swift forums.  Using the release switch is an okay work-around in terms of my specific project, which doesn't have much code, but obviously it is untenable for a larger code base.  Most of the code for my project is in a module, and that doesn't get recompiled with the release switch.
